version: "3"

services:
  azure_spa_login:
    build:
      context: ../
      dockerfile: ./deploy/azure_spa_login/Dockerfile
    image: azure_spa_login:development
    container_name: azure_spa_login
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    expose:
      - 8080
    ports:
      - ${APP_PORT}:8080
    env_file:
      - ./azure_spa_login/.env
    volumes:
      - ../azure_spa_login/:/usr/src/azure_spa_login
    networks:
      - azure_spa_login_network


networks: 
  azure_spa_login_network:
    driver: bridge
