version: "3"

services:
  xtk_front:
    build:
      context: ../
      dockerfile: ./deploy/xtk_front/Dockerfile
    image: xtk_front:development
    container_name: xtk_front
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    expose:
      - 8080
    ports:
      - ${APP_PORT}:8080
    env_file:
      - ./xtk_front/.env
    volumes:
      - ../xtk_front/:/usr/src/xtk_front
    networks:
      - xtk_front_network


networks: 
  xtk_front_network:
    driver: bridge
